# png_to_ssd1306.R
#
# Converts a collection of PNG images to arrays of raw data that can be
# fed directly to the SSD1306 OLED driver.
#
# Copyright (c) 2025 Colin Luoma

library(glue)
library(png)

# convert a sequence of binary digits to a decimal number
binary_to_decimal <- function(x) {
  char_vec <- as.character(x) |>
    strsplit("") |>
    unlist()
  char_vec <- (char_vec == 1) |>
    rev() |>
    which()
  char_vec <- char_vec - 1
  char_vec <- 2^char_vec |>
    sum()
  return(char_vec)
}

png_to_oled_buffer <- function(filename) {
  img<-readPNG(filename)
  
  # compress image data to black and white using a very simple heuristic
  img_bw <- (img[,,1] + img[,,1] + img[,,1]) / 3
  img_bw <- apply(img_bw, c(1,2), FUN = \(x) {if(x > 0.3) 1L else 0L}, simplify = FALSE)
  
  # create image buffer data
  img_buf <- NULL
  for (i in seq(1, nrow(img_bw), 8)) {
    for (j in seq(1, ncol(img_bw), 1)) {
      img_buf <- c(img_buf, binary_to_decimal(rev(img_bw[i:(i+7), j])))
    }
  }
  
  return(img_buf)
}

data_to_c_array <- function(array_name, data) {
  ar <- paste0("const uint8_t ", array_name, "[", length(data), "] = {\n\t")
  
  for (i in 1:(length(data)-1)) {
    ar <- c(
      ar,
      sprintf("0x%02X,", data[i])
    )
    if (i %% 32 == 0)
      ar <- c(ar, "\n\t")
  }
  ar <- c(ar, sprintf("0x%02X\n", data[length(data)]))
  
  ar <- c(ar, "};")
  
  return(paste0(ar, collapse = ""))
}

write_to_c_files <- function(name, data) {
  
  append_to_c_file <- function(x) {
    write(x, file = paste0(name, ".c"), append = TRUE)
  }
  append_to_h_file <- function(x) {
    write(x, file = paste0(name, ".h"), append = TRUE)
  }
  
  # C
  write("", file = paste0(name, ".c"))
  append_to_c_file("#include <stdint.h>\n")
  for (buffer in data) {
    append_to_c_file(data_to_c_array(buffer$array_name, buffer$buf))
    append_to_c_file("")
  }
  
  # H
  write("", file = paste0(name, ".h"))
  append_to_h_file("// This file is autogenerated")
  append_to_h_file(glue("#ifndef {name}", name = paste0(toupper(name), "_H")))
  append_to_h_file(glue("#define {name}", name = paste0(toupper(name), "_H")))
  append_to_h_file("#include <stdint.h>\n")
  for (buffer in data) {
    append_to_h_file(paste0("extern const uint8_t ", buffer$array_name, "[", length(buffer$buf), "];"))
    append_to_h_file("")
  }
  append_to_h_file(glue("#endif // {name}", name = paste0(toupper(name), "_H")))
}


write_to_c_files(
  name = "oled_static_data",
  data = list(
    list(array_name="oled_one",   buf=png_to_oled_buffer("one.png")),
    list(array_name="oled_two",   buf=png_to_oled_buffer("two.png")),
    list(array_name="oled_three", buf=png_to_oled_buffer("three.png")),
    list(array_name="oled_four",  buf=png_to_oled_buffer("four.png")),
    list(array_name="oled_five",  buf=png_to_oled_buffer("five.png")),
    list(array_name="oled_six",   buf=png_to_oled_buffer("six.png")),
    list(array_name="oled_seven", buf=png_to_oled_buffer("seven.png")),
    list(array_name="oled_eight", buf=png_to_oled_buffer("eight.png")),
    list(array_name="oled_nine",  buf=png_to_oled_buffer("nine.png")),
    list(array_name="oled_zero",  buf=png_to_oled_buffer("zero.png")),
    list(array_name="oled_colon", buf=png_to_oled_buffer("colon.png")),
    list(array_name="oled_sun", buf=png_to_oled_buffer("sun.png")),
    list(array_name="oled_moon", buf=png_to_oled_buffer("moon.png")),
    list(array_name="oled_pm", buf=png_to_oled_buffer("pm.png")),
    list(array_name="oled_am", buf=png_to_oled_buffer("am.png"))
  )
)
