
// This file is autogenerated
#ifndef OLED_STATIC_DATA_H
#define OLED_STATIC_DATA_H
#include <stdint.h>

extern const uint8_t oled_one[64];

extern const uint8_t oled_two[64];

extern const uint8_t oled_three[64];

extern const uint8_t oled_four[64];

extern const uint8_t oled_five[64];

extern const uint8_t oled_six[64];

extern const uint8_t oled_seven[64];

extern const uint8_t oled_eight[64];

extern const uint8_t oled_nine[64];

extern const uint8_t oled_zero[64];

extern const uint8_t oled_colon[16];

extern const uint8_t oled_sun[512];

extern const uint8_t oled_moon[512];

#endif // OLED_STATIC_DATA_H
